set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set -g focus-events on

set -wg mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set -sg escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin '2kabhishek/tmux2k'

set -g @tmux2k-theme 'default'
set -g @tmux2k-icons-only false

set -g @tmux2k-left-plugins 'session'
set -g @tmux2k-right-plugins 'updates docker cwd'

set -g @tmux2k-session-format '#W'
set -g @tmux2k-session-icon ''

set -g @tmux2k-window-list-left-sep ' '
set -g @tmux2k-window-list-right-sep ' '

set -g @tmux2k-cwd-length 15
set -g @tmux2k-cwd-min-depth 4

set -g @tmux2k-bg-main '#1e1e2e'
set -g @tmux2k-text '#cdd6f4'
set -g @tmux2k-message-bg '#eba0ac'
set -g @tmux2k-message-fg '#1e1e2e'
set -g @tmux2k-pane-active-border '#f5c2e7'
set -g @tmux2k-pane-border '#7f849c'
set -g @tmux2k-prefix-highlight '#fab387'

set -g @tmux2k-white '#cdd6f4'
set -g @tmux2k-gray '#7f849c'
set -g @tmux2k-black '#1e1e2e'
set -g @tmux2k-blue '#89b4fa'
set -g @tmux2k-green '#a6e3a1'
set -g @tmux2k-orange '#fab387'
set -g @tmux2k-pink '#f5c2e7'
set -g @tmux2k-purple '#cba6f7'
set -g @tmux2k-red '#f38ba8'
set -g @tmux2k-yellow '#f9e2af'

set -g @tmux2k-session-colors 'purple black'
set -g @tmux2k-window-list-colors 'white black'
set -g @tmux2k-updates-colors 'green black'
set -g @tmux2k-docker-colors 'blue black'
set -g @tmux2k-cwd-colors 'black white'

run '~/.tmux/plugins/tpm/tpm'
