# TMUX CONFIGURATION FILE

# TERMINAL
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',xterm-256color:RGB'

# GENERAL
set -sg escape-time 0
set -g focus-events on
set -g mouse on
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# PREFIX
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# SPLITS
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# RELOAD
unbind r
bind r source-file ~/.tmux.conf	\; display-message "Configuration reloaded."

# PANES RESIZE
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# BUFFER NAVIGATION & COPY MODE
set -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin '2kabhishek/tmux2k'

# PLUGINS CONFIGURATION

# TMUX2K
set -g @tmux2k-theme 'default'
set -g @tmux2k-icons-only false

set -g @tmux2k-left-plugins 'session'
set -g @tmux2k-right-plugins 'updates docker cwd'

set -g @tmux2k-session-format '#W'
set -g @tmux2k-session-icon ''

set -g @tmux2k-cwd-length 15
set -g @tmux2k-cwd-min-depth 4

set -g @tmux2k-bg-main '#1a1b26'
set -g @tmux2k-text '#c0caf5'
set -g @tmux2k-message-bg '#1a1b26'
set -g @tmux2k-message-fg '#c0caf5'
set -g @tmux2k-pane-active-border '#7aa2f7'
set -g @tmux2k-pane-border '#292e42'
set -g @tmux2k-prefix-highlight '#ff9e64'

set -g @tmux2k-white '#c0caf5'
set -g @tmux2k-gray '#565f89'
set -g @tmux2k-black '#1a1b26'
set -g @tmux2k-blue '#7aa2f7'
set -g @tmux2k-green '#9ece6a'
set -g @tmux2k-orange '#ff9e64'
set -g @tmux2k-pink '#bb9af7'
set -g @tmux2k-purple '#9d7cd8'
set -g @tmux2k-red '#f7768e'
set -g @tmux2k-yellow '#e0af68'

set -g @tmux2k-session-colors 'purple black'
set -g @tmux2k-window-list-colors 'black white'
set -g @tmux2k-updates-colors 'green black'
set -g @tmux2k-docker-colors 'blue black'
set -g @tmux2k-cwd-colors 'black white'

run '~/.tmux/plugins/tpm/tpm'
